[package]
name = "bevy-behavior-tree"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

#[workspace]
#resolver = "2"

[dependencies]
bevy = "0.7"


